ALLOWED_ORIGINS = ["http://localhost:3000", "https://inkling-project.vercel.app"]
ALLOWED_METHODS = ["GET", "POST", "OPTIONS"]
ALLOWED_HEADERS = ["Content-Type"]
ROUTE_USER_MESSAGES = "/api/user-messages"
KEY_TYPE = "type"
KEY_USER_MESSAGE = "userMessage"
KEY_TIMESTAMP = "timestamp"
SENDER_USER = "user"
SENDER_AI = "ai"
ERROR_DOC_INSERT = "Failed to insert document into the database"
ERROR_DOC_FIND = "Failed to retrieve user messages from the database"
